Update composer.json
zaporylie/drush-drupal-settings pull request #1
Opened 2017-10-27 11:51 UTC by eiriksm

2017-10-27 14:01 UTC, eiriksm commented
Now tested and works. Also needed the correct bootstrap annotation.

2017-10-30 07:44 UTC, zaporylie requested changes
Left some inline comments.

2017-10-30 07:44 UTC, zaporylie commented on composer.json
> +        "drush/drush": "^8.1 || ^9@beta"
Let's only support for ^9@beta here. If someone needs support for Drush:8,  ^0.2 is the way to go. That also means - remove old command definition.

2017-10-30 07:44 UTC, zaporylie commented on drush.services.yml
> +services:
Do we need this file?

2017-10-30 07:44 UTC, zaporylie commented on src/Commands/DrupalSettingsCommands.php
> +<?php
This file should be deleted in favour of src/Commands/DrupalSettingsCommands.php?

2017-10-30 07:44 UTC, zaporylie commented on src/Commands/drupal_settings/DrupalSettingsCommands.php
> +use Drupal\Core\DrupalKernel;
This is unused.

2017-10-30 07:44 UTC, zaporylie commented on src/Commands/drupal_settings/DrupalSettingsCommands.php
> +use Symfony\Component\HttpFoundation\Request;
This is unused.

2017-10-30 07:44 UTC, zaporylie commented on src/Commands/drupal_settings/DrupalSettingsCommands.php
> +class DrupalSettingsCommands extends DrushCommands {
Maybe remove `Drupal` part and leave simple `SettingsCommands`?

2017-10-30 21:15 UTC, closed without merging